# Generated by Django 5.1.3 on 2025-01-04 11:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Отключена')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код промокода')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка (%)')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала действия')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='Лимит использования')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('card_description', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('slug', models.SlugField(unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='product_files/', verbose_name='Файл для скачивания')),
                ('is_best_seller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
